language: node_js
sudo: false
cache:
  directories:
    - ~/.npm
notifications:
  email: false

node_js:
  - '9'
  - '8'

branches:
  only:
    - master
    - next
    - /^greenkeeper.*$/

before_install:
- npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
  - npm run verify

after_script: greenkeeper-lockfile-upload

after_success:
  - npm install --no-save coveralls && npm run coveralls
  - npm run semantic-release
